version: '3.8'

services:
  # Service de base de donn√©es
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mon_atelier
      MYSQL_USER: user_atelier
      MYSQL_PASSWORD: password_atelier
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Service Application PHP
  app:
    build: .
    ports:
      - "8081"
    depends_on:
      - db